services:
  - type: web
    name: places-in-time-chatbot
    env: static
    plan: starter
    buildCommand: "echo 'No build command needed for static site'"
    staticPublishPath: "./static_frontend"
    routes:
      - type: rewrite
        source: /user/:id/threads
        destination: /threads.html