services:
  - type: web
    name: places-in-time-chatbot
    runtime: python
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONPATH
        value: .
