services:
  - type: web
    name: places-in-time-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: PYTHONPATH=. python -m backend.main
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true

