services:
  - type: web
    name: places-in-time-backend
    env: python
    plan: free
    workingDirectory: . # Keep this at the root
    buildCommand: pip install -r backend/requirements.txt
    # CHANGE START COMMAND to run your entrypoint.py
    startCommand: python entrypoint.py
    envVars:
      - key: PORT
        value: "10000"
    autoDeploy: true
